[package]
name = "llama-simple"
version = "0.14.1"
edition = "2021"

[dependencies]
wasmedge-wasi-nn = "0.8.0"
clap = { version = "4.4.6", features = ["cargo"] }
once_cell = "1.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
