[workspace]
members = ["llama-api-server", "chat-prompts", "endpoints", "llama-core"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
endpoints = { path = "endpoints", version = "^0.5" }
chat-prompts = { path = "chat-prompts", version = "^0.5" }
llama-core = { path = "llama-core" }
thiserror = "1"
