name: "Bug Report"
description: Running WasmEdge LLM, but it's not working as you expect?
title: "bug: "
labels: [
  "bug"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Please shortly describe what bug you encounter.
      placeholder: Describe in a few lines about the bug
    validations:
      required: true
  - type: textarea
    id: reproducuction_steps
    attributes:
      label: "Reproduction steps"
      description: Please provide as much information as necessary to reproduce the bug.
      placeholder: |
        1. How to install '...'
        2. Execute with models '....'
        3. Execute with inputs and flags '....'
        4. Get error
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Any logs you want to share for showing the specific issue"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    validations:
      required: false
  - type: input
    id: model
    attributes:
      label: "Model Information"
      description: Model Information
      placeholder: e.g. llama2-7b-chat_Q5_K_M.gguf, etc.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: "Operating system information"
      description: Operating system information
      placeholder: e.g. Ubuntu 20.04, CentOS 7.6, macOS 13.5.2, or Windows 11, etc.
    validations:
      required: true
  - type: input
    id: arch
    attributes:
      label: "ARCH"
      description: ARCH
      placeholder: e.g. amd64, x86_64, arm64, aarch64, or RISC-V, etc.
    validations:
      required: true
  - type: input
    id: cpu
    attributes:
      label: "CPU Information"
      description: CPU Information
      placeholder: e.g. Intel i7-12700, AMD 5900X, or Apple M2 Max, etc.
    validations:
      required: true
  - type: input
    id: memory
    attributes:
      label: "Memory Size"
      description: Memory Size
      placeholder: e.g. 8GB, 16GB, or 64GB, etc.
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: "GPU Information"
      description: GPU Information
      placeholder: e.g. GTX 1080, NVIDIA Orin, or Apple M3, etc.
    validations:
      required: true
  - type: input
    id: vram
    attributes:
      label: "VRAM Size"
      description: VRAM Size
      placeholder: e.g. 4GB, 8GB, or 16GB, etc.
    validations:
      required: true
