name: Build

on:
  push:
    branches:
      - dev
      - main
      - release-*
      - feat-*
      - ci-*
      - refactor-*
      - fix-*
      - test-*
    paths:
      - '.github/workflows/**'
      - '**/Cargo.toml'
      - '**/*.rs'
      - '**/*.sh'
  pull_request:
    branches:
      - dev
      - main
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/**'
      - '**/Cargo.toml'
      - '**/*.rs'
      - '**/*.sh'

jobs:
  build-wasm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-13]
    steps:
      - name: Clone project
        id: checkout
        uses: actions/checkout@v3

      - name: Install Rust-nightly
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-wasip1
          components: rustfmt, clippy

      - name: Install Rust-stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip1

      - name: Build simple
        id: build_simple
        run: |
          cd simple
          RUSTFLAGS="--cfg wasmedge --cfg tokio_unstable" cargo +nightly fmt --all -- --check
          RUSTFLAGS="--cfg wasmedge --cfg tokio_unstable" cargo +nightly clippy --target wasm32-wasip1 -- -D warnings
          RUSTFLAGS="--cfg wasmedge --cfg tokio_unstable" cargo build --target wasm32-wasip1 --release

      - name: Build chat
        id: build_chat
        run: |
          cd chat
          RUSTFLAGS="--cfg wasmedge --cfg tokio_unstable" cargo +nightly fmt --all -- --check
          RUSTFLAGS="--cfg wasmedge --cfg tokio_unstable" cargo +nightly clippy --target wasm32-wasip1 -- -D warnings
          RUSTFLAGS="--cfg wasmedge --cfg tokio_unstable" cargo build --target wasm32-wasip1 --release

      - name: Build api-server
        id: build_api_server
        run: |
          cd api-server
          RUSTFLAGS="--cfg wasmedge --cfg tokio_unstable" cargo +nightly fmt --all -- --check
          RUSTFLAGS="--cfg wasmedge --cfg tokio_unstable" cargo +nightly clippy --target wasm32-wasip1 -- -D warnings
          RUSTFLAGS="--cfg wasmedge --cfg tokio_unstable" cargo build --target wasm32-wasip1 --release
